<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Company>NathanKell</Company>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
     <OutputPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\Mods\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\net6\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\net6\Il2CppInterop.Runtime.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppMessagePack">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\Il2CppMessagePack.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\Il2Cppmscorlib.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppNewtonsoft.Json">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\Il2CppNewtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppSystem">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\Il2CppSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppSystem.Core">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\Il2CppSystem.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="MelonLoader">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\net6\MelonLoader.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\Unity.TextMeshPro.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\UnityEngine.IMGUIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.InputModule">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\UnityEngine.InputModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.Physics2DModule">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\UnityEngine.Physics2DModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\UnityEngine.UIModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy /Y &quot;$(TargetDir)TweaksAndFixes.dll&quot; &quot;F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\Mods\TweaksAndFixes.dll&quot;&#xD;&#xA;copy /Y &quot;$(TargetDir)TweaksAndFixes.dll&quot; &quot;F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\Mods\TAFData&quot;&#xD;&#xA;xcopy /Y /S &quot;$(ProjectDir)\Assets\*&quot; &quot;F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\Mods\&quot;" />
  </Target>

</Project>
