<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TweaksAndFixes\TweaksAndFixes.csproj">
      <Private>False</Private>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\net6\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\net6\Il2CppInterop.Runtime.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\Il2Cppmscorlib.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppSystem">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\Il2CppSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Il2CppSystem.Core">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\Il2CppSystem.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="MelonLoader">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\net6\MelonLoader.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\UnityEngine.PhysicsModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>F:\Games\Ultimate.Admiral.Dreadnoughts.1.7.0.0\game\MelonLoader\Il2CppAssemblies\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy /y $(TargetPath) &quot;C:\Games\Steam\steamapps\common\Ultimate Admiral Dreadnoughts\Mods\UADRealism.dll&quot;&#xD;&#xA;copy /y ..\English.lng &quot;C:\Games\Steam\steamapps\common\Ultimate Admiral Dreadnoughts\Ultimate Admiral Dreadnoughts_Data\StreamingAssets\Languages\English.lng&quot;" />
  </Target>
</Project>
