//#define LOGHULLSTATS
//#define LOGHULLSCALES
//#define LOGPARTSTATS
//#define LOGGUNSTATS

using MelonLoader;
using UnityEngine;
using Il2Cpp;
using UnityEngine.UI;
using Il2CppTMPro;
using TweaksAndFixes.Harmony;
using static Il2Cpp.Ship;

#pragma warning disable CS8600
#pragma warning disable CS8602
#pragma warning disable CS8603
#pragma warning disable CS8604
#pragma warning disable CS8618
#pragma warning disable CS8625

// TODO: Add popup to lng file, catch other game breaking errors, add to params

namespace TweaksAndFixes
{
    public class PredefinedDesignsData
    {
        public class PredefData
        {
            [Serializer.Field] public string name;
            [Serializer.Field] public string filename;
            [Serializer.Field] public float skipChance;
            [Serializer.Field] public int yearRange;
            public readonly Dictionary<string, List<int>> yearsPerPlayer = new Dictionary<string, List<int>>();
            public bool loadedData = false;
            public float _curSkipChance;
        }

        private static PredefinedDesignsData? _Instance = null;

        private static void Ensure()
        {
            if (_Instance == null)
            {
                _Instance = new PredefinedDesignsData();
            }
            if (!_Instance._loaded)
                _Instance.LoadData();
        }

        public static PredefinedDesignsData Instance
        {
            get
            {
                Ensure();
                return _Instance;
            }
        }

        private const string _StockAssetName = "<stock predefined designs>";
        private const string _StockAssetFilenameProxy = "--";
        public static GameObject? _BatchGenUI = null;

        private bool _loaded = false;
        private bool _noFile = true;
        private bool _lastLoadCared = false;
        public bool LastLoadWasRestrictive => _lastLoadCared;
        private readonly List<PredefData> _predefFileData = new List<PredefData>();
        private int _lastValidData = 0;
        private bool _needUseNewFindCode = false;
        public bool NeedUseNewFindCode => _needUseNewFindCode;
        private static bool PredefinedDesignFileProblem = false;
        public static bool NeedLoadRestrictive(bool prewarm)
            => CampaignController.Instance.designsUsage == CampaignController.DesignsUsage.FullPredefined ||
                            (prewarm && CampaignController.Instance.designsUsage != CampaignController.DesignsUsage.FullGenerated);

        private void LoadData()
        {
            _loaded = false;
            _predefFileData.Clear();
            Patch_GameManager.CurrentSubGameState = Patch_GameManager.SubGameState.LoadingPredefinedDesigns;

            string text;
            if (Config._PredefinedDesignsDataFile.Exists)
            {
                _noFile = false;
                text = File.ReadAllText(Config._PredefinedDesignsDataFile.path);
            }
            else if (Config._PredefinedDesignsFile.Exists)
            {
                _noFile = false;
                text = $"@name,filename,skipChance,yearRange\n{Config._PredefinedDesignsFile.name.Replace(".bin", "")},{Config._PredefinedDesignsFile.name},0,-1";
            }
            else
            {
                _noFile = true;
                text = $"@{nameof(PredefData.name)},{nameof(PredefData.filename)},{nameof(PredefData.skipChance)},{nameof(PredefData.yearRange)}\nAutogenerated,{Config._PredefinedDesignsFile},0,-1";
            }

            // If a file is specified, even if it uses stock assets, it may use
            // a yearRange. So we can't trust it. And if we're not clobbering
            // tech, then we need to use the new logic.
            _needUseNewFindCode = !_noFile || Config.DontClobberTechForPredefs;

            Melon<TweaksAndFixes>.Logger.Msg("Loading predefined design database");
            Serializer.CSV.Read<List<PredefData>, PredefData>(text, _predefFileData);
            Patch_GameManager.CurrentSubGameState = Patch_GameManager.SubGameState.Other;
            _loaded = true;
        }

        public bool LoadPredefSets(bool prewarm)
        {
            if (PredefinedDesignFileProblem) return false;

            int totalCount = 0;
            _lastValidData = 0;
            _lastLoadCared = false; // if we fail, remember this load as less restrictive
            int iC = _predefFileData.Count;
            bool isLast = true;
            bool loadedNonStock = false;
            bool careAboutPredefs = NeedLoadRestrictive(prewarm);

            for (int i = iC; i-- > 0;)
            {
                var data = _predefFileData[i];
                data.yearsPerPlayer.Clear();
                data.loadedData = false;

                string? path;
                string errorFilename;
                if (data.filename == _StockAssetFilenameProxy)
                {
                    path = null;
                    errorFilename = _StockAssetName;
                }
                else
                {
                    errorFilename = data.filename;
                    path = Path.Combine(Config._BasePath, data.filename);
                    if (!File.Exists(path))
                    {
                        if (_noFile)
                        {
                            path = null;
                            errorFilename = _StockAssetName;
                        }
                        else
                        {
                            Melon<TweaksAndFixes>.Logger.Error($"Failed to find predefined designs file {errorFilename} referenced in {Config._PredefinedDesignsDataFile}");
                            if (careAboutPredefs)
                                return false;
                            else
                                continue;
                        }
                    }
                }

                bool careAboutThisPredef = isLast && careAboutPredefs && Config.Param("taf_predef_ignore_missing", 0) == 0;
                if (!LoadPredefs(path, out var store, out int dCount, careAboutThisPredef))
                {
                    Melon<TweaksAndFixes>.Logger.Error($"Tried to load predefined designs file {errorFilename} but failed to load it correctly.");
                    if (careAboutThisPredef)
                        return false;
                    else
                        continue;
                }

                if (path != null)
                    loadedNonStock = true;

                if (isLast)
                {
                    isLast = false;
                    _lastValidData = i;
                    data._curSkipChance = 0;
                    CampaignController.Instance._currentDesigns = CampaignDesigns.FromStore(store);
                    if (_needUseNewFindCode)
                    {
                        foreach (var spy in store.shipsPerYear)
                        {
                            foreach (var spp in spy.Value.shipsPerPlayer)
                            {
                                data.yearsPerPlayer.ValueOrNew(spp.Key).Add(spy.Key);
                            }
                        }
                    }
                }
                else
                {
                    data._curSkipChance = data.skipChance;
                    foreach (var spy in store.shipsPerYear)
                    {
                        foreach (var spp in spy.Value.shipsPerPlayer)
                        {
                            data.yearsPerPlayer.ValueOrNew(spp.Key).Add(spy.Key);

                            string pName = $"{i}_{spp.Key}";
                            foreach (var spt in spp.Value.shipsPerType)
                            {
                                foreach (var ship in spt.Value)
                                {
                                    var oldName = ship.playerName;
                                    ship.playerName = pName;
                                    CampaignController.Instance._currentDesigns.AddShip(ship);
                                    ship.playerName = oldName;
                                }
                            }
                        }
                    }
                }
                foreach (var kvp in data.yearsPerPlayer)
                    kvp.Value.Sort();

                totalCount += dCount;
                data.loadedData = true;
                Melon<TweaksAndFixes>.Logger.Msg($"Loaded {dCount} designs from {errorFilename}");
            }
            if (loadedNonStock)
                Melon<TweaksAndFixes>.Logger.Msg($"Overrode predefined designs by loading {totalCount} ships.");
            _lastLoadCared = prewarm;
            return true;
        }

        public static bool LoadPredefs(string? path, out CampaignDesigns.Store? store, out int dCount, bool checkMissing)
        {
            dCount = 0;
            if (path == null)
            {
                path = _StockAssetName; // for logging
                var textAsset = Resources.Load<TextAsset>("packedShips");
                store = Util.DeserializeObjectByte<CampaignDesigns.Store>(textAsset.bytes);
            }
            else
            {
                var bytes = File.ReadAllBytes(path);
                store = Util.DeserializeObjectByte<CampaignDesigns.Store>(bytes);
                if (store == null)
                    return false;
            }

            if (store.shipsPerYear == null)
            {
                Melon<TweaksAndFixes>.Logger.Error("Failed to load shipsPerYear from " + path);
                return false;
            }

            if (Config.Param("taf_predef_debug_enable", 0) == 1) // Check for predef problems
            {
                int min = Config.Param("taf_predef_debug_min_ship_count", 5);
                int max = Config.Param("taf_predef_debug_max_ship_count", 15);
                bool asCSV = Config.Param("taf_predef_debug_format", 0) == 1;
                bool printAll = Config.Param("taf_predef_debug_print_all", 0) == 1;
                List<string> types = new List<string> { "tb", "dd", "cl", "ca", "bc", "bb" }; // TODO: Pull from shiptypes.csv instead!

                string ShipsPerYearProblems = "";

                // foreach (var spy in store.shipsPerYear)
                // {
                //     Melon<TweaksAndFixes>.Logger.Error($"{spy.Key}");
                //     foreach (var spp2 in spy.Value.shipsPerPlayer)
                //     {
                //         Melon<TweaksAndFixes>.Logger.Error($"  {spp2.Key}");
                //         foreach (var spp3 in spp2.value.shipsPerType)
                //         {
                //             Melon<TweaksAndFixes>.Logger.Error($"    {spp3.Key}: {spp3.Value.Count}");
                //         }
                //     }
                // }
                // 
                // 
                // if (false)
                foreach (var spy in store.shipsPerYear)
                {
                    bool yearProblem = false;
                    foreach (var p in G.GameData.playersMajor.Values)
                    {
                        bool missing = true;
                        foreach (var spp2 in spy.Value.shipsPerPlayer)
                        {
                            if (spp2.Key == p.name && spp2.Value.shipsPerType.Count > 0)
                            {
                                missing = false;
                                break;
                            }
                        }
                        if (missing)
                        {
                            if (!yearProblem)
                            {
                                yearProblem = true;
                                ShipsPerYearProblems += asCSV ? $"\n,,,,,,,\n{spy.Key},tb,dd,cl,ca,bc,bb" : $"\n - {spy.Key}";
                            }
                            ShipsPerYearProblems += asCSV ? $"\n{p.name},0,0,0,0,0,0" : $"\n   = {p.name}: No Designs"; // \n  + tb: 0\n  + dd: 0\n  + cl: 0\n  + ca: 0\n  + bc: 0\n  + bb: 0
                            continue;
                        }
                    }


                    foreach (var spp2 in spy.Value.shipsPerPlayer)
                    {
                        string msg = asCSV ? $"\n{spp2.key}" : $"\n   = {spp2.key}:";
                        bool countryProblem = false;
                        string typeCount = "";
                        int typeIndex = 0;
                        var sppp1 = spp2.value.shipsPerType;

                        Dictionary<string, Il2CppSystem.Collections.Generic.List<Ship.Store>> parsedList = new Dictionary<string, Il2CppSystem.Collections.Generic.List<Ship.Store>>();
                        foreach (var spp3 in spp2.value.shipsPerType)
                        {
                            parsedList[spp3.Key] = spp3.Value;
                        }

                        for (int i = 0; i < types.Count; i++)
                        {
                            if (!parsedList.ContainsKey(types[i]))
                            {
                                typeCount += ",0";
                                if (!asCSV) msg += $"\n     + {types[i]}: 0";
                                countryProblem = true;
                                if (!yearProblem)
                                {
                                    yearProblem = true;
                                    ShipsPerYearProblems += asCSV ? $"\n,,,,,,,\n{spy.Key},tb,dd,cl,ca,bc,bb" : $"\n - {spy.Key}";
                                }
                                continue;
                            }

                            var shipList = parsedList[types[i]];

                            typeIndex += 2;
                            bool isTBorDD = i < 2;
                            if (shipList.Count < (isTBorDD ? min * 2 : min) || shipList.Count > (isTBorDD ? max * 2 : max) || printAll)
                            {
                                msg += asCSV ? "" : $"\n     + {types[i]}: {shipList.Count}";
                                typeCount += $",{shipList.Count}";

                                countryProblem = true;
                                if (!yearProblem)
                                {
                                    yearProblem = true;
                                    ShipsPerYearProblems += asCSV ? $"\n,,,,,,,\n{spy.Key},tb,dd,cl,ca,bc,bb" : $"\n - {spy.Key}";
                                }
                            }
                            else
                            {
                                typeCount += ",";
                            }
                        }
                        if (countryProblem) 
                        {
                            ShipsPerYearProblems += msg + (asCSV ? typeCount : "");
                        }
                    }
                }

                if (ShipsPerYearProblems.Length > 0)
                {
                    Melon<TweaksAndFixes>.Logger.Error($"Found problems with pregen design file. See Wiki for more info on pregen files:{ShipsPerYearProblems}");

                    G.ui.ShowMessage(LocalizeManager.Localize("$TAF_Ui_Predef_Error_MalformedPredefFile"),
                        new System.Action(() =>
                        {
                            GameManager.Quit();
                        })
                    );

                    PredefinedDesignFileProblem = true;

                    return false;
                }
            }

            bool failed = false;

            foreach (var spy in store.shipsPerYear)
            {
                if (spy.Value.shipsPerPlayer == null)
                {
                    Melon<TweaksAndFixes>.Logger.Error($"Failed to load shipsPerPlayer for {spy.Key} from {path}");
                    failed = true;
                    break;
                }

                foreach (var p in G.GameData.playersMajor.Values)
                {
                    if (checkMissing)
                    {
                        bool missing = true;
                        foreach (var spp2 in spy.Value.shipsPerPlayer)
                        {
                            if (spp2.Key == p.name)
                            {
                                missing = false;
                                break;
                            }
                        }
                        if (missing)
                        {
                            Melon<TweaksAndFixes>.Logger.Error($"Year {spy.Key} lacks nation {p.name} from {path}");
                            failed = true;
                            break;
                        }
                    }
                }

                if (failed)
                {
                    break;
                }

                foreach (var spp in spy.Value.shipsPerPlayer)
                {
                    if (spp.Value.shipsPerType == null)
                    {
                        Melon<TweaksAndFixes>.Logger.Error($"Failed to load shipsPerType for {spy.Key} and player {spp.Key} from {path}");
                        failed = true;
                        break;
                    }

                    foreach (var spt in spp.Value.shipsPerType)
                    {
                        if (spt.Value == null)
                        {
                            Melon<TweaksAndFixes>.Logger.Error($"Failed to load ship list for type {spt.Key} for {spy.Key} and player {spp.Key} from {path}");
                            failed = true;
                            break;
                        }

                        dCount += spt.Value.Count;
                    }

                    if (failed)
                    {
                        break;
                    }
                }

                if (failed)
                {
                    break;
                }
            }


            if (failed)
            {
                G.ui.ShowMessage(LocalizeManager.Localize("$TAF_Ui_Predef_Error_MalformedPredefFile"),
                    new System.Action(() =>
                    {
                        GameManager.Quit();
                    })
                );

                PredefinedDesignFileProblem = true;

                return false;
            }

            return !failed;
        }

        public Ship.Store GetRandomShip(Player player, ShipType type, int desiredYear)
        {
            string pName = player.data.name;

            int maxTechYear = desiredYear; //Config.DontClobberTechForPredefs ? CampaignControllerM.CachePlayerTechs(player, true) : desiredYear;
            if (maxTechYear < Config.StartingYear)
                maxTechYear = Config.StartingYear;

            for (int i = 0; i < _predefFileData.Count; ++i)
            {
                var data = _predefFileData[i];
                if (!data.loadedData || data.skipChance > UnityEngine.Random.value || !data.yearsPerPlayer.TryGetValue(pName, out var ypp))
                {
                    continue;
                }

                string sppName =  i == _lastValidData ? pName : $"{i}_{pName}";

                int tries = -10;
                for (int j = ypp.Count; j-- > 0;)
                {
                    int year = ypp[j];
                    if (year > maxTechYear)
                    {
                        continue;
                    }
                    if (data.yearRange >= 0 ? year < maxTechYear - data.yearRange : tries++ > 0)
                    {
                        if (tries >= 0) Melon<TweaksAndFixes>.Logger.Error($"Predefined designs: After 10 tries, failed to find design of type {type.name} for {player.Name(false)} in year {desiredYear}.");
                        break;
                    }

                    if (!CampaignController.Instance._currentDesigns.shipsPerYear.TryGetValue(year, out var spy) || !spy.shipsPerPlayer.TryGetValue(sppName, out var spp))
                    {
                        Melon<TweaksAndFixes>.Logger.Error($"Predefined designs: yearsPerPlayer claims year {year} exists but no spp for player {pName} exists here!");
                        if(spy != null)
                        {
                            string lstr = "Year " + year;
                            foreach (var spp2 in spy.shipsPerPlayer)
                            {
                                lstr += " " + spp2.Key;
                            }
                            Debug.Log(lstr);
                        }
                        Debug.Log("********** Full State of CD:");
                        foreach (var spy2 in CampaignController.Instance._currentDesigns.shipsPerYear)
                        {
                            string lstr = "Year " + spy2.Key;
                            foreach (var spp2 in spy2.Value.shipsPerPlayer)
                            {
                                lstr += " " + spp2.Key;
                            }
                            Debug.Log(lstr);
                        }
                        continue;
                    }

                    var ship = spp.RandomShipOfType(player, type);

                    // if (ship == null && spp.shipsPerType.ContainsKey(type.name) && spp.shipsPerType[type.name].Count > 0)
                    // {
                    //      var shipList = spp.shipsPerType[type.name];
                    //  
                    //      int index = UnityEngine.Random.RandomRange(0, shipList.Count - 1);
                    //  
                    //      ship = shipList[index];
                    // }

                    // if (spp.shipsPerType[type.name] != null)
                    // {
                    //     Melon<TweaksAndFixes>.Logger.Error($"{year}: Searching through {spp.shipsPerType[type.name].Count} designs of type {type.name} for {player.Name(false)}...");
                    // }

                    if (ship != null)
                    {
                        // if (Config.DontClobberTechForPredefs)
                        //     CampaignControllerM.CleanupSDCaches();
                        // Melon<TweaksAndFixes>.Logger.Error($"  Found {ship.hullName} in {desiredYear} from {year}.");
                        return ship;
                    }
                    // else
                    // {
                    //     Melon<TweaksAndFixes>.Logger.Error($"  Failed after {10 + tries} tries, trying again...");
                    // }
                }
            }
            // if (Config.DontClobberTechForPredefs)
            //     CampaignControllerM.CleanupSDCaches();

            return null;
        }

        public class BatchShipGeneratorConfig
        {
            [Serializer.Field] public string name;
            [Serializer.Field] public string value;
        }

        private static readonly Dictionary<string, BatchShipGeneratorConfig> BatchShipGeneratorConfigData = new();
        private static bool hasBSGConfig = false;

        public static void AddUIforBSG()
        {
            if (Config._BatchShipGeneratorConfigDataFile.Exists)
            {
                string text = File.ReadAllText(Config._BatchShipGeneratorConfigDataFile.path);
                List<BatchShipGeneratorConfig> list = new();
                Serializer.CSV.Read<List<BatchShipGeneratorConfig>, BatchShipGeneratorConfig>(text, list);

                foreach (var val in list)
                {
                    BatchShipGeneratorConfigData[val.name] = val;
                }

                hasBSGConfig = true;
            }

            if (_BatchGenUI != null)
            {
                GameObject.DestroyImmediate(_BatchGenUI);
                _BatchGenUI = null;
            }

            _BatchGenUI = GameObject.Instantiate(G.ui.popupUi.FindDeepChild("FileConverter").gameObject);
            GameObject.Destroy(_BatchGenUI.GetComponent<SaveFilesConverter>());
            GameObject.Destroy(_BatchGenUI.GetComponent<CanvasRenderer>());
            GameObject.Destroy(_BatchGenUI.GetComponent<Image>());
            _BatchGenUI.transform.SetParent(null);
            var root = _BatchGenUI.transform.Find("Root").gameObject;
            root.transform.Find("JsonFiles").gameObject.SetActive(false);

            var years = root.transform.Find("BinFiles").gameObject;
            years.name = "YearsList";
            var yearsList = years.transform.Find("Viewport").Find("List").gameObject;
            yearsList.DestroyAllChilds();
            var listVLG = yearsList.GetOrAddComponent<VerticalLayoutGroup>();
            var fsmNew = GameObject.Instantiate(G.ui.gameObject.FindDeepChild("Fullscreen Mode"));
            var toggleTemplate = fsmNew.GetComponentInChildren<Toggle>();
            var label = fsmNew.transform.Find("Label");
            label.SetParent(toggleTemplate.gameObject);
            GameObject.Destroy(label.GetComponent<LayoutElement>());
            toggleTemplate.SetParent(yearsList);
            toggleTemplate.gameObject.AddComponent<HorizontalLayoutGroup>();
            var go = new GameObject("dummy");
            go.AddComponent<RectTransform>();
            go.transform.SetParent(toggleTemplate.transform);
            var bg = toggleTemplate.transform.Find("Background").gameObject;
            var le = bg.AddComponent<LayoutElement>();
            le.minWidth = 20f;
            toggleTemplate.SetActive(false);
            GameObject.DestroyImmediate(fsmNew);

            var buttons = root.transform.Find("Buttons");
            var start = buttons.transform.Find("Close").GetComponent<Button>();
            start.name = "Start";
            start.onClick.RemoveAllListeners();
            var yearsO = buttons.transform.Find("Convert").GetComponent<Button>();
            yearsO.name = "OpenYears";
            yearsO.onClick.RemoveAllListeners();
            yearsO.SetActive(false);
            var yearsC = buttons.transform.Find("Delete").GetComponent<Button>();
            yearsC.name = "CloseYears";
            yearsC.onClick.RemoveAllListeners();
            yearsC.SetActive(false);

            var upperRow = root.transform.Find("UpperButtons").gameObject;
            upperRow.DestroyAllChilds();
            var res = G.ui.gameObject.FindDeepChild("Resolution");
            var nationDropObj = GameObject.Instantiate(res, upperRow.transform);
            var typeDropObj = GameObject.Instantiate(res, upperRow.transform);
            var bugT = G.ui.popupUi.FindDeepChild("BugReport").FindDeepChild("Title");
            var numInputObj = GameObject.Instantiate(bugT, upperRow.transform);

            var progressBox = root.transform.Find("CheckingSaves").gameObject;
            progressBox.SetParent(_BatchGenUI);
            var pcv = progressBox.AddComponent<Canvas>();
            var pcs = progressBox.AddComponent<CanvasScaler>();

            var rcv = root.AddComponent<Canvas>();
            var rcs = root.AddComponent<CanvasScaler>();

            var ucv = G.ui.GetComponent<Canvas>();
            var ucs = G.ui.GetComponent<CanvasScaler>();
            var ugr = G.ui.GetComponent<GraphicRaycaster>();

            pcv.renderMode = rcv.renderMode = ucv.renderMode;
            pcv.worldCamera = rcv.worldCamera = ucv.worldCamera;
            pcs.referenceResolution = rcs.referenceResolution = ucs.referenceResolution;
            pcs.screenMatchMode = rcs.screenMatchMode = ucs.screenMatchMode;
            pcs.uiScaleMode = rcs.uiScaleMode = ucs.uiScaleMode;
            var pgr = progressBox.AddComponent<GraphicRaycaster>();
            var rgr = root.AddComponent<GraphicRaycaster>();



            progressBox.SetActive(false);
            root.SetActive(false);

            _BatchGenUI.SetActive(true);

            //Melon<TweaksAndFixes>.Logger.Msg("Created batcher UI");

            var bsg = _BatchGenUI.AddComponent<BatchShipGenerator>();
            bsg.yearsButton = yearsO;
            bsg.yearsPanel = years;
            bsg.yearToggleParent = yearsList.transform;
            bsg.yearTemplate = toggleTemplate;
            bsg.closeYearsPanel = yearsC;
            bsg.startButton = start;
            bsg.shipsAmount = numInputObj.GetComponentInChildren<TMP_InputField>();
            bsg.shipTypeDropdown = typeDropObj.GetComponentInChildren<TMP_Dropdown>();
            bsg.nationDropdown = nationDropObj.GetComponentInChildren<TMP_Dropdown>();
            bsg.InitRoot = root;
            bsg.UIRoot = progressBox;
            bsg.progress = progressBox.GetComponentInChildren<TextMeshProUGUI>();
            //Melon<TweaksAndFixes>.Logger.Msg("Setup BSG");
            MelonCoroutines.Start(FixBSGText(numInputObj, typeDropObj, nationDropObj));
        }

        internal static System.Collections.IEnumerator FixBSGText(GameObject numInputObj, GameObject typeDropObj, GameObject nationDropObj)
        {
            // TODO: We could just keep the LocalizeText component?
            yield return new WaitForEndOfFrame();
            var bsg = _BatchGenUI.GetComponent<BatchShipGenerator>();
            var root = bsg.InitRoot;

            var locs = bsg.gameObject.GetComponentsInChildren<LocalizeText>(true);
            for (int i = locs.Length; i-- > 0;)
                GameObject.Destroy(locs[i]);
            yield return new WaitForEndOfFrame();

            root.transform.Find("Header").GetComponent<TextMeshProUGUI>().text = LocalizeManager.Localize("$TAF_Ui_BatchShipGenerator_Title");
            root.transform.Find("Note").GetComponent<TextMeshProUGUI>().text = LocalizeManager.Localize("$TAF_Ui_BatchShipGenerator_Note");
            bsg.startButton.GetComponentInChildren<TextMeshProUGUI>().text = LocalizeManager.Localize("$TAF_Ui_BatchShipGenerator_Generate");
            bsg.yearsButton.GetComponentInChildren<TextMeshProUGUI>().text = LocalizeManager.Localize("$TAF_Ui_BatchShipGenerator_ShowYears");
            bsg.closeYearsPanel.GetComponentInChildren<TextMeshProUGUI>().text = LocalizeManager.Localize("$TAF_Ui_BatchShipGenerator_HideYears");
            nationDropObj.transform.Find("Label").GetComponent<TextMeshProUGUI>().text = LocalizeManager.Localize("$TAF_Ui_BatchShipGenerator_Nations");
            typeDropObj.transform.Find("Label").GetComponent<TextMeshProUGUI>().text = LocalizeManager.Localize("$TAF_Ui_BatchShipGenerator_Types");
            numInputObj.FindDeepChild("Placeholder").GetComponent<TextMeshProUGUI>().text = LocalizeManager.Localize("$TAF_Ui_BatchShipGenerator_NumShips");

            if (hasBSGConfig)
            {
                List<int> years = new();

                if (BatchShipGeneratorConfigData["show_years"].value == "1")
                {
                    bsg.yearsButton.onClick.Invoke();

                    int min = int.MaxValue;
                    int max = int.MinValue;

                    if (BatchShipGeneratorConfigData["year_min"].value.Length != 0 && !int.TryParse(BatchShipGeneratorConfigData["year_min"].value, out min))
                    {
                        Melon<TweaksAndFixes>.Logger.Error($"BatchShipGeneratorConfigData Error: `year_min` must be a valid integer `{BatchShipGeneratorConfigData["year_min"].value}`");
                    }

                    if (BatchShipGeneratorConfigData["year_max"].value.Length != 0 && !int.TryParse(BatchShipGeneratorConfigData["year_max"].value, out max))
                    {
                        Melon<TweaksAndFixes>.Logger.Error($"BatchShipGeneratorConfigData Error: `year_max` must be a valid integer `{BatchShipGeneratorConfigData["year_max"].value}`");
                    }

                    List<int> select = new();

                    if (BatchShipGeneratorConfigData["year_list"].value.Length != 0)
                    {
                        foreach (var val in BatchShipGeneratorConfigData["year_list"].value.Replace(" ", "").Split(","))
                        {
                            int parse = 0;

                            if (!int.TryParse(val, out parse))
                            {
                                Melon<TweaksAndFixes>.Logger.Error($"BatchShipGeneratorConfigData Error: `year_list` values must be a valid integers `{val}`");
                                continue;
                            }

                            select.Add(parse);
                        }
                    }

                    foreach (var child in bsg.yearToggleParent.GetChildren())
                    {
                        string text = child.GetChild("Label").GetComponent<TextMeshProUGUI>().text;

                        if (text == "Fullscreen Mode") continue;

                        int year = 0;

                        if (!int.TryParse(text, out year))
                        {
                            Melon<TweaksAndFixes>.Logger.Error($"Failed to parse `{text}`");
                            continue;
                        }

                        if ((year < min || year > max) && (select.Count == 0 || !select.Contains(year))) continue;

                        years.Add(year);
                    }
                }

                string nation = "all";

                if (BatchShipGeneratorConfigData["nation"].value.Length != 0)
                {
                    nation = BatchShipGeneratorConfigData["nation"].value;
                }

                string type = "all";

                if (BatchShipGeneratorConfigData["ship_type"].value.Length != 0)
                {
                    type = BatchShipGeneratorConfigData["ship_type"].value;
                }

                int count = 10;

                if (BatchShipGeneratorConfigData["generate_count"].value.Length != 0 && !int.TryParse(BatchShipGeneratorConfigData["generate_count"].value, out count))
                {
                    Melon<TweaksAndFixes>.Logger.Error($"BatchShipGeneratorConfigData Error: `generate_count` must be a valid integer `{BatchShipGeneratorConfigData["generate_count"].value}`");
                }

                Patch_BatchShipGenerator.ConfigureBSG(bsg, nation, type, years, count);
            }
        }
    }

    //class PredefinedDesignsDataAsync
    //{
    //    public class PredefDataAsync
    //    {
    //        [Serializer.Field] public string name;
    //        [Serializer.Field] public string filename;
    //        [Serializer.Field] public int skipChance;
    //        [Serializer.Field] public int yearRange;
    //        public readonly Dictionary<string, List<int>> yearsPerPlayer = new Dictionary<string, List<int>>();
    //    }
    //
    //    private static List<Task<Utils.MockCampaignDesignsStore>> loadTasks = new();
    //    private static List<Task<Utils.MockCampaignDesignsStore>> mergeTasks = new();
    //    private static List<Task<Utils.MockCampaignDesignsStore>> verifyTasks = new();
    //    public static List<Utils.MockCampaignDesignsStore> predefData = new();
    //
    //    private static bool loadedCSV = false;
    //    private static bool noFile = true;
    //    private static bool working = false;
    //    private static bool loadingFiles = false;
    //    private static bool mergingFiles = false;
    //    private static bool varifyingFiles = false;
    //    private static bool predefsLoaded = false;
    //    private static bool predefsErrored = false;
    //    private static readonly List<PredefDataAsync> fileData = new();
    //
    //    public static void LoadData()
    //    {
    //        loadedCSV = false;
    //        fileData.Clear();
    //        Patch_GameManager.CurrentSubGameState = Patch_GameManager.SubGameState.LoadingPredefinedDesigns;
    //
    //        string text;
    //        if (Config._PredefinedDesignsDataFile.Exists)
    //        {
    //            noFile = false;
    //            text = File.ReadAllText(Config._PredefinedDesignsDataFile.path);
    //        }
    //        else if (Config._PredefinedDesignsFile.Exists)
    //        {
    //            noFile = false;
    //            text = $"@name,filename,skipChance,yearRange\n{Config._PredefinedDesignsFile.name.Replace(".bin", "")},{Config._PredefinedDesignsFile.name},0,-1";
    //        }
    //        else
    //        {
    //            noFile = true;
    //            text = $"@{nameof(PredefData.name)},{nameof(PredefData.filename)},{nameof(PredefData.skipChance)},{nameof(PredefData.yearRange)}\nAutogenerated,--,0,-1";
    //        }
    //
    //        Melon<TweaksAndFixes>.Logger.Msg("Loading predefined design database");
    //        Serializer.CSV.Read<List<PredefDataAsync>, PredefDataAsync>(text, fileData);
    //        Patch_GameManager.CurrentSubGameState = Patch_GameManager.SubGameState.Other;
    //        loadedCSV = true;
    //    }
    //
    //    public static PredefDataAsync GetDataAtIndex(int index)
    //    {
    //        return (index >= 0 || index < fileData.Count) ? fileData[index] : null;
    //    }
    //
    //    public static bool hasOverride()
    //    {
    //        return !noFile;
    //    }
    //
    //    public static void StoreToBinTaf(string path, CampaignDesigns.Store store, bool split = false)
    //    {
    //        Melon<TweaksAndFixes>.Logger.Msg($"Converting UAD Campaign Designs Store to Bin Taf file...");
    //
    //        if (store == null)
    //        {
    //            Melon<TweaksAndFixes>.Logger.Error($"  STORE WAS NULL!");
    //            return;
    //        }
    //
    //        Utils.MockCampaignDesignsStore mockStore = new(store);
    //        mockStore.CountData();
    //
    //        Melon<TweaksAndFixes>.Logger.Msg($"  Created Mock Store!");
    //
    //        var rawBin = MessagePackSerializer.Serialize(mockStore);
    //
    //        if (rawBin == null)
    //        {
    //            Melon<TweaksAndFixes>.Logger.Error($"  FAILED TO SERIALIZE!");
    //            return;
    //        }
    //
    //        // Melon<TweaksAndFixes>.Logger.Msg($"  Testing");
    //
    //        // var deserial = MessagePackSerializer.Deserialize<Utils.MockCampaignDesignsStore>(rawBin);
    //
    //        if (split)
    //        {
    //            Melon<TweaksAndFixes>.Logger.Msg($"Paste the following text into predefinedDesigns.csv (use a raw text editor)");
    //            foreach (var spy in mockStore.SplitByPlayer())
    //            {
    //                if (File.Exists($"{path}_{spy.Key}.bintaf"))
    //                {
    //                    Melon<TweaksAndFixes>.Logger.Warning($"Found existing file at path {$"{path}_{spy.Key}.bintaf"}. Replacing with new file.");
    //                    File.Delete($"{path}_{spy.Key}.bintaf");
    //                }
    //
    //                StoreToBinTaf($"{path}_{spy.Key}.bintaf", spy.Value);
    //                Melon<TweaksAndFixes>.Logger.Msg($"PredefinedDesigns_{spy.Key},PredefinedDesigns_{spy.Key}.bintaf,0");
    //            }
    //        }
    //        else
    //        {
    //            if (File.Exists($"{path}.bintaf"))
    //            {
    //                Melon<TweaksAndFixes>.Logger.Warning($"Found existing file at path {$"{path}.bintaf"}. Replacing with new file.");
    //                File.Delete($"{path}.bintaf");
    //            }
    //
    //            Melon<TweaksAndFixes>.Logger.Msg($"Paste the following text into predefinedDesigns.csv (use a raw text editor)");
    //            StoreToBinTaf($"{path}.bintaf", mockStore);
    //            Melon<TweaksAndFixes>.Logger.Msg($"PredefinedDesigns,PredefinedDesigns.bintaf,0");
    //        }
    //    }
    //
    //    public static void ShipStoreToBinTaf(string path, MockShipsStore store)
    //    {
    //        var bytes = MessagePackSerializer.Serialize<Utils.MockShipsStore>(store);
    //
    //        var compBytes = ModUtils.Compress(bytes);
    //
    //        if (compBytes == null)
    //        {
    //            Melon<TweaksAndFixes>.Logger.Msg($"Failed to compress!");
    //            return;
    //        }
    //
    //        File.WriteAllBytes(path, compBytes);
    //    }
    //
    //    public static MockShipsStore BinTafToShipStore(string path)
    //    {
    //        var compBytes = File.ReadAllBytes(path);
    //
    //        if (compBytes == null)
    //        {
    //            Melon<TweaksAndFixes>.Logger.Msg($"Failed to load bytes!");
    //            return null;
    //        }
    //
    //        var bytes = ModUtils.Decompress(compBytes);
    //
    //        if (bytes == null)
    //        {
    //            Melon<TweaksAndFixes>.Logger.Msg($"Failed to compress!");
    //            return null;
    //        }
    //
    //        return MessagePackSerializer.Deserialize<Utils.MockShipsStore>(bytes);
    //    }
    //
    //    public static void BinToBinTaf()
    //    {
    //        Melon<TweaksAndFixes>.Logger.Msg($"Converting UAD Bin file to Bin Taf file...");
    //
    //        string binPath = "G:\\Games\\Steam\\steamapps\\common\\Ultimate Admiral Dreadnoughts\\Mods\\predefinedDesigns.bin";
    //        string tafPath = "G:\\Games\\Steam\\steamapps\\common\\Ultimate Admiral Dreadnoughts\\Mods\\predefinedDesigns.bintaf";
    //
    //        var bytes = File.ReadAllBytes(binPath);
    //
    //        Melon<TweaksAndFixes>.Logger.Msg($"  Loaded {bytes.Length} bytes!");
    //
    //        CampaignDesigns.Store store = Util.DeserializeObjectByte<CampaignDesigns.Store>(bytes);
    //
    //        if (store == null)
    //        {
    //            Melon<TweaksAndFixes>.Logger.Msg($"  FAILED TO DESERIALZIE!");
    //            return;
    //        }
    //
    //        Melon<TweaksAndFixes>.Logger.Msg($"  Deserialized!");
    //
    //        Utils.MockCampaignDesignsStore mockStore = new(store);
    //
    //        Melon<TweaksAndFixes>.Logger.Msg($"  Created Mock Store!");
    //
    //        var rawBin = MessagePackSerializer.Serialize(mockStore);
    //
    //        if (rawBin == null)
    //        {
    //            Melon<TweaksAndFixes>.Logger.Msg($"  FAILED TO SERIALIZE!");
    //            return;
    //        }
    //
    //        Melon<TweaksAndFixes>.Logger.Msg($"  Testing");
    //
    //        var deserial = MessagePackSerializer.Deserialize<Utils.MockCampaignDesignsStore>(rawBin);
    //
    //        Melon<TweaksAndFixes>.Logger.Msg($"  Compressing BIN");
    //        var tafBytes = ModUtils.Compress(rawBin);
    //        File.WriteAllBytes(tafPath, tafBytes);
    //    }
    //
    //    public static Utils.MockCampaignDesignsStore BinTafToStore(string path, PredefDataAsync data = null)
    //    {
    //        var compBytes = File.ReadAllBytes(path);
    //
    //        if (compBytes == null)
    //        {
    //            Melon<TweaksAndFixes>.Logger.Msg($"Failed to load path!");
    //            return null;
    //        }
    //
    //        var bytes = ModUtils.Decompress(compBytes);
    //
    //        var store = MessagePackSerializer.Deserialize<Utils.MockCampaignDesignsStore>(bytes);
    //
    //        if (data != null)
    //        {
    //            store.CountData();
    //            store.SetDataOrigin(fileData.IndexOf(data));
    //        }
    //
    //        return store;
    //    }
    //
    //    public static void StoreToBinTaf(string path, Utils.MockCampaignDesignsStore store)
    //    {
    //        var bytes = MessagePackSerializer.Serialize<Utils.MockCampaignDesignsStore>(store);
    //
    //        var compBytes = ModUtils.Compress(bytes);
    //
    //        if (compBytes == null)
    //        {
    //            Melon<TweaksAndFixes>.Logger.Msg($"Failed to compress!");
    //            return;
    //        }
    //
    //        File.WriteAllBytes(path, compBytes);
    //    }
    //
    //    public static bool CheckAsyncTaskListCompleted(List<Task<Utils.MockCampaignDesignsStore>> tasks)
    //    {
    //        foreach (Task t in tasks)
    //        {
    //            if (!t.IsCompleted) return false;
    //        }
    //
    //        return true;
    //    }
    //
    //    public static List<int> CheckAsyncTaskListErrors(List<Task<Utils.MockCampaignDesignsStore>> tasks)
    //    {
    //        List<int> errorIndexes = new();
    //
    //        for (int i = 0; i < tasks.Count; i++)
    //        {
    //            if (tasks[i].IsFaulted) errorIndexes.Add(i);
    //        }
    //
    //        return errorIndexes;
    //    }
    //
    //    public static void DisposeAsyncTasks(List<Task<Utils.MockCampaignDesignsStore>> tasks)
    //    {
    //        for (int i = tasks.Count - 1; i >= 0; i--)
    //        {
    //            if (!tasks[i].IsCompleted) continue;
    //
    //            tasks[i].Dispose();
    //            tasks.RemoveAt(i);
    //        }
    //    }
    //
    //    public static void UpdatePredefLoading()
    //    {
    //        if (!working || predefsErrored) return;
    //
    //        if (loadingFiles && CheckAsyncTaskListCompleted(loadTasks))
    //        {
    //            var errors = CheckAsyncTaskListErrors(loadTasks);
    //
    //            if (errors.Count > 0)
    //            {
    //                Melon<TweaksAndFixes>.Logger.Msg("Some predef files failed to load: (Predefs will not work!)");
    //
    //                foreach (var errorIndex in errors)
    //                {
    //                    Melon<TweaksAndFixes>.Logger.Msg($"  {fileData[errorIndex].filename}");
    //                }
    //
    //                predefsErrored = true;
    //
    //                return;
    //            }
    //
    //            Melon<TweaksAndFixes>.Logger.Msg("Finished loading predef files successfully.");
    //
    //            loadingFiles = false;
    //
    //            MergePredefSetsAsync();
    //        }
    //        else if (mergingFiles && CheckAsyncTaskListCompleted(mergeTasks))
    //        {
    //            var errors = CheckAsyncTaskListErrors(loadTasks);
    //
    //            if (errors.Count > 0)
    //            {
    //                Melon<TweaksAndFixes>.Logger.Msg("Some predef files failed to merge: (Predefs will not work!)");
    //
    //                foreach (var errorIndex in errors)
    //                {
    //                    Melon<TweaksAndFixes>.Logger.Msg($"  Merge ID {errorIndex}");
    //                }
    //
    //                predefsErrored = true;
    //
    //                return;
    //            }
    //
    //            // TODO: Sort by skip chance
    //            foreach (var t in mergeTasks)
    //            {
    //                predefData.Add(t.Result);
    //            }
    //
    //            Melon<TweaksAndFixes>.Logger.Msg($"Finished merging predef files successfully.");
    //            Melon<TweaksAndFixes>.Logger.Msg($"Total ships = {predefData[0].shipCount} | Year range {predefData[0].yearMin} - {predefData[0].yearMax}");
    //
    //            // foreach (var spy in predefData[0].SplitByPlayer())
    //            // {
    //            //     // StoreToBinTaf($"{Config._BasePath}\\PredefinedDesigns\\PredefinedDesigns_{spy.Key}.bintaf", spy.Value);
    //            //     Melon<TweaksAndFixes>.Logger.Msg($"PredefinedDesigns_{spy.Key},PredefinedDesigns_{spy.Key}.bintaf");
    //            // }
    //
    //            DisposeAsyncTasks(loadTasks);
    //            DisposeAsyncTasks(mergeTasks);
    //
    //            predefsLoaded = true;
    //            mergingFiles = false;
    //            working = false;
    //        }
    //    }
    //
    //    public static void HaltUntilDoneLoadingPredefs()
    //    {
    //        if (!working || predefsErrored) return;
    //
    //        Melon<TweaksAndFixes>.Logger.Msg($"Waiting for predefs to finish loading...");
    //
    //        UpdatePredefLoading();
    //
    //        if (loadingFiles)
    //        {
    //            foreach (var t in loadTasks)
    //            {
    //                t.Wait();
    //            }
    //
    //            UpdatePredefLoading();
    //        }
    //        
    //        if (mergingFiles)
    //        {
    //            foreach (var t in mergeTasks)
    //            {
    //                t.Wait();
    //            }
    //
    //            UpdatePredefLoading();
    //        }
    //    }
    //
    //    public static bool LoadPredefSetsAsync(bool reload)
    //    {
    //        if ((predefsLoaded || predefsErrored) && !reload) return false;
    //
    //        if (loadingFiles || working) return false;
    //        predefsLoaded = false;
    //        predefsErrored = false;
    //        loadingFiles = true;
    //        working = true;
    //
    //        Melon<TweaksAndFixes>.Logger.Msg("Loading predef files asynchronously:");
    //
    //        bool isLast = true;
    //        bool loadedNonStock = false;
    //
    //        for (int i = fileData.Count; i-- > 0;)
    //        {
    //            var data = fileData[i];
    //            data.yearsPerPlayer.Clear();
    //
    //            string? path;
    //            string errorFilename;
    //            if (data.filename == "--")
    //            {
    //                path = null;
    //                errorFilename = "<stock predefined designs>";
    //            }
    //            else
    //            {
    //                errorFilename = data.filename;
    //                path = Path.Combine(Config._BasePath, data.filename);
    //                if (!File.Exists(path))
    //                {
    //                    if (noFile)
    //                    {
    //                        path = null;
    //                        errorFilename = "<stock predefined designs>";
    //                    }
    //                    else
    //                    {
    //                        Melon<TweaksAndFixes>.Logger.Error($"  Failed to find predefined designs file {errorFilename} referenced in {Config._PredefinedDesignsDataFile}");
    //                        continue;
    //                    }
    //                }
    //            }
    //
    //            Melon<TweaksAndFixes>.Logger.Msg($"  Queueing [{errorFilename}] predef file...");
    //
    //            Task<Utils.MockCampaignDesignsStore> task = Task<Utils.MockCampaignDesignsStore>.Run(() => {
    //                if (path == null)
    //                {
    //                    // var textAsset = Resources.Load<TextAsset>("packedShips");
    //                    return new Utils.MockCampaignDesignsStore(); //Util.DeserializeObjectByte<CampaignDesigns.Store>(textAsset.bytes);
    //                }
    //                else
    //                {
    //                    var store = BinTafToStore(path, data);
    //                    return store;
    //                }
    //            });
    //
    //            loadTasks.Add(task);
    //
    //            if (path != null)
    //                loadedNonStock = true;
    //        }
    //
    //        if (loadedNonStock)
    //            Melon<TweaksAndFixes>.Logger.Msg($"Queued {fileData.Count} files to load asynchronously.");
    //
    //        return true;
    //    }
    //
    //    private static bool MergePredefSetsAsync()
    //    {
    //        if (predefsLoaded || predefsErrored) return false;
    //
    //        if (mergingFiles || loadingFiles || !working) return false;
    //        mergingFiles = true;
    //
    //        Dictionary<int, List<int>> sameChance = new();
    //        Dictionary<int, string> sameChanceLog = new();
    //
    //        for (int i = 0; i < fileData.Count; i++)
    //        {
    //            int chance = fileData[i].skipChance;
    //
    //            sameChance.ValueOrNew(chance).Add(i);
    //
    //            if (!sameChanceLog.ContainsKey(chance)) sameChanceLog[chance] = $"{chance}% skip chance files:";
    //
    //            sameChanceLog[chance] += $" {fileData[i].filename}";
    //        }
    //
    //        Melon<TweaksAndFixes>.Logger.Msg($"Found {sameChance.Count} unique probabilities among {fileData.Count} predef files, queueing file merging:");
    //
    //        foreach (var group in sameChance)
    //        {
    //            Melon<TweaksAndFixes>.Logger.Msg($"  Queuing merge of {sameChanceLog[group.Key]}");
    //
    //            Task<Utils.MockCampaignDesignsStore> task = Task<Utils.MockCampaignDesignsStore>.Run(() => {
    //                Utils.MockCampaignDesignsStore root = loadTasks[group.Value[0]].Result;
    //                for (int i = 1; i < group.Value.Count; i++)
    //                {
    //                    root.Merge(loadTasks[group.Value[i]].Result);
    //                }
    //
    //                return root;
    //            });
    //
    //            mergeTasks.Add(task);
    //        }
    //        return true;
    //    }
    //
    //    public static Ship.Store GetRandomShip(Player player, ShipType type, int desiredYear)
    //    {
    //        string pName = player.data.name;
    //
    //        int maxTechYear = desiredYear; //Config.DontClobberTechForPredefs ? CampaignControllerM.CachePlayerTechs(player, true) : desiredYear;
    //        if (maxTechYear < Config.StartingYear)
    //            maxTechYear = Config.StartingYear;
    //        // if (maxTechYear > Config.Param("campaign_max_year", 1960))
    //        //     maxTechYear = Config.Param("campaign_max_year", 1960);
    //
    //        for (int i = 0; i < predefData.Count; ++i)
    //        {
    //            var data = predefData[i];
    //            
    //            if (data.dataIndex > UnityEngine.Random.value * 100)
    //            {
    //                continue;
    //            }
    //
    //            if (data.dataIndex != 0)
    //            {
    //                var result = data.GetRandomShip(player, type, desiredYear);
    //
    //                if (result == null) continue;
    //
    //                // TODO: Expensive
    //                return result.toStore();
    //            }
    //            else
    //            {
    //                for (int tries = 0; tries < 10; tries++)
    //                {
    //                    var result = data.GetRandomShip(player, type, desiredYear - tries);
    //
    //                    if (result == null) continue;
    //
    //                    // TODO: Expensive
    //                    return result.toStore();
    //                }
    //
    //                Melon<TweaksAndFixes>.Logger.Error($"Failed to find predefined design of type {type.name} for {pName} in year {desiredYear}!");
    //            }
    //        }
    //
    //        return null;
    //    }
    //
    //    private static bool VerifyPredefSetsAsync()
    //    {
    //        if (varifyingFiles || mergingFiles || loadingFiles || !working) return false;
    //        varifyingFiles = true;
    //
    //        Melon<TweaksAndFixes>.Logger.Msg("VerifyPredefSetsAsync");
    //
    //        foreach (var task in mergeTasks)
    //        {
    //            
    //        }
    //
    //        var data = fileData[0];
    //        data.yearsPerPlayer.Clear();
    //
    //        var loadStore = loadTasks[0].Result;
    //
    //        if (loadStore == null)
    //        {
    //            Melon<TweaksAndFixes>.Logger.Error("Failed to load shipsPerYear!");
    //            loadTasks.Clear();
    //            return false;
    //        }
    //
    //        CampaignController.Instance._currentDesigns = new CampaignDesigns();
    //
    //        foreach (var spy in loadStore.shipsPerYear)
    //        {
    //            foreach (var spp in spy.Value.shipsPerPlayer)
    //            {
    //                data.yearsPerPlayer.ValueOrNew(spp.Key).Add(spy.Key);
    //
    //                foreach (var spt in spp.Value.shipsPerType)
    //                {
    //                    foreach (var ship in spt.Value)
    //                    {
    //                        //var oldName = ship.playerName;
    //                        //ship.playerName = pName;
    //                        // CampaignController.Instance._currentDesigns.AddShip(ship.Il2CppStore);
    //                        //ship.playerName = oldName;
    //                    }
    //                }
    //            }
    //        }
    //
    //        foreach (var kvp in data.yearsPerPlayer)
    //            kvp.Value.Sort();
    //
    //        Melon<TweaksAndFixes>.Logger.Msg("Finished Parsing!");
    //
    //        return true;
    //    }
    //}

    // ShipsPerPlayer.RandomShipOfType
    // 
    // [HarmonyPatch(typeof(ShipsPerPlayer))]
    // internal class ShipsPerPlayer_RandomShipOfType
    // {
    //     [HarmonyPatch(nameof(ShipsPerPlayer.RandomShipOfType))]
    //     [HarmonyPrefix]
    //     internal static bool Postfix_RandomShipOfType(ShipsPerPlayer __instance, ref Ship.Store __result, Player player, ShipType shipType)
    //     {
    //         Melon<TweaksAndFixes>.Logger.Error($"{player.Name(false)} has {__instance.validDesigns.Count} valid designs.");
    // 
    //         var shipList = __instance.shipsPerType[shipType.name];
    // 
    //         if (shipList.Count == 0) return false;
    // 
    //         int index = UnityEngine.Random.RandomRange(0, shipList.Count - 1);
    // 
    //         __result = shipList[index];
    // 
    //         return false;
    //     }
    // }
}